# Web server settings used when starting the application with: python main.py
server:
  # Use 127.0.0.1 for access from this computer only.
  # Use 0.0.0.0 to allow access from other computers on your network.
  host: 0.0.0.0
  port: 6769

  # Automatically restart the development server after Python code changes.
  # Set this to false for a production deployment.
  reload: true
